name: text_speech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  go_router: ^14.2.1

  audioplayers: ^6.0.0
  record: 6.1.2

  file_picker: ^8.0.0
  flutter_sound: ^9.3.0

  provider: ^6.1.2
  http: ^1.2.1
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - .env

# ✅ L10N BURADA OLACAK (flutter bloğundan sonra, eş seviyede)
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  synthetic-package: true
